core/urls.py
from django.urls import path
from core import views as v


app_name = 'core'


urlpatterns = [
    path('', v.index, name='index'),
]

estoque/urls.py
from django.urls import path
from estoque import views as v


app_name = 'estoque'


urlpatterns = [
    path('', v.estoque_entrada_list, name='estoque_entrada_list'),
    path('<int:pk>/', v.estoque_entrada_detail, name='estoque_entrada_detail'),
    path('add/', v.estoque_entrada_add, name='estoque_entrada_add'),
    path('saida/', v.estoque_saida_list, name='estoque_saida_list'),
]

produto/urls.py
from django.urls import path
from produto import views as v


app_name = 'produto'


urlpatterns = [
    path('', v.produto_list, name='produto_list'),
    path('<int:pk>/', v.produto_detail, name='produto_detail'),
    path('add/', v.ProdutoCreate.as_view(), name='produto_add'),
    path('<int:pk>/edit', v.ProdutoUpdate.as_view(), name='produto_edit'),
    path('<int:pk>/json', v.produto_json, name='produto_json'),
]

projeto/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('core.urls')),
    path('produto/', include('produto.urls')),
    path('estoque/', include('estoque.urls')),
    path('admin/', admin.site.urls),
]

core/models.py
from django.db import models

class TimeStampedModel(models.Model):
    created = models.DateTimeField(
        'criado em',
        auto_now_add=True,
        auto_now=False
    )
    modified = models.DateTimeField(
        'modificado em',
        auto_now_add=False,
        auto_now=True
    )

    class Meta:
        abstract = True

estoque/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse_lazy
from core.models import TimeStampedModel
from produto.models import Produto
from .managers import EstoqueEntradaManager, EstoqueSaidaManager


MOVIMENTO = (
    ('e', 'entrada'),
    ('s', 'saída'),
)

class Estoque(TimeStampedModel):
    funcionario = models.ForeignKey(User, on_delete=models.CASCADE)
    nf = models.PositiveIntegerField('nota fiscal', null=True, blank=True)
    movimento = models.CharField(max_length=1, choices=MOVIMENTO)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return '{} - {} - {}'.format(self.pk, self.nf, self.created.strftime('%d - %m - %Y'))

    def get_absolute_url(self):
        return reverse_lazy("estoque:estoque_entrada_detail", kwargs={"pk": self.pk})
    

    def nf_formated(self):
        return str(self.nf).zfill(3)


class EstoqueEntrada(Estoque):

    objects = EstoqueEntradaManager()

    class Meta:
        proxy = True
        verbose_name = 'estoque estrada'
        verbose_name_plural = 'estoque entrada'


class EstoqueSaida(Estoque):

    objects = EstoqueSaidaManager()

    class Meta:
        proxy = True
        verbose_name = 'estoque saída'
        verbose_name_plural = 'estoque saída'


class EstoqueItens(models.Model):
    estoque = models.ForeignKey(
        Estoque, 
        on_delete=models.CASCADE, 
        related_name='estoques'
    )
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
    quantidade = models.PositiveIntegerField()
    saldo = models.PositiveIntegerField()

    class Meta:
        ordering = ('pk',)

    def __str__(self):
        return '{} - {} - {}'.format(self.pk, self.estoque.pk, self.produto)

produto/models.py
from django.db import models
from django.urls import reverse_lazy


class Produto(models.Model):
    importado = models.BooleanField(default=False)
    ncm = models.CharField('NCM', max_length=8)
    produto = models.CharField(max_length=100, unique=True)
    preco = models.DecimalField('preço', max_digits=7, decimal_places=2)
    estoque = models.IntegerField('estoque atual')
    estoque_minimo = models.PositiveIntegerField('estoque mínimo', default=0)

    class Meta:
        ordering = ('produto',)

    def __str__(self):
        return self.produto

    def get_absolute_url(self):
        return reverse_lazy('produto:produto_detail', kwargs={'pk': self.pk})

    def to_dict_json(self):
        return {
            'pk': self.pk,
            'produto': self.produto,
            'estoque': self.estoque,
        }

estoque/forms.py
from django import forms
from .models import Estoque, EstoqueItens


class EstoqueForm(forms.ModelForm):

    class Meta:
        model = Estoque
        fields = '__all__'

class EstoqueItensForm(forms.ModelForm):

    class Meta:
        model = EstoqueItens
        fields = '__all__'

produto/forms.py
from django import forms
from .models import Produto


class ProdutoForm(forms.ModelForm):

    class Meta:
        model = Produto
        fields = '__all__'

core/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'index.html')

estoque/views.py
from django.forms import inlineformset_factory
from django.http import HttpResponseRedirect
from django.shortcuts import render, resolve_url
from produto.models import Produto
from .models import Estoque, EstoqueEntrada, EstoqueSaida, EstoqueItens
from .forms import EstoqueForm, EstoqueItensForm


def estoque_entrada_list(request):
    template_name = 'estoque_entrada_list.html'
    objects = EstoqueEntrada.objects.all()
    context = {'object_list': objects}
    return render(request, template_name, context)

def estoque_entrada_detail(request, pk):
    template_name = 'estoque_entrada_detail.html'
    obj = EstoqueEntrada.objects.get(pk=pk)
    context = {'object': obj}
    return render(request, template_name, context)

def dar_baixa_estoque(form):
    # Pega os produtos a partir da instância do formulário (Estoque).Estoque
    produtos = form.estoques.all()
    for item in produtos:
        produto = Produto.objects.get(pk=item.produto.pk)
        produto.estoque = item.saldo
        produto.save()
    print('Estoque atualizado com sucesso.')

def estoque_entrada_add(request):
    template_name = 'estoque_entrada_form.html'
    estoque_form = Estoque()
    item_estoque_formset = inlineformset_factory(
        EstoqueEntrada,
        EstoqueItens,
        form=EstoqueItensForm,
        extra=0,
        min_num=1,
        validate_min=True,
    )
    if request.method == 'POST':
        form = EstoqueForm(request.POST, instance=estoque_form, prefix='main')
        formset = item_estoque_formset(
            request.POST,
            instance=estoque_form, 
            prefix='estoque'
        )
        if form.is_valid() and formset.is_valid():
            form = form.save()
            formset.save()
            dar_baixa_estoque(form)
            url = 'estoque:estoque_entrada_detail'
            return HttpResponseRedirect(resolve_url(url, form.pk))
    else:
        form = EstoqueForm(instance=estoque_form, prefix='main')
        formset = item_estoque_formset(instance=estoque_form, prefix='estoque')
    
    context = {'form':form, 'formset':formset}
    return render(request, template_name, context)

def estoque_saida_list(request):
    template_name = 'estoque_saida_list.html'
    objects = EstoqueSaida.objects.all()
    context = {'object_list': objects}
    return render(request, template_name, context)

produto/views.py
from django.http import JsonResponse
from django.shortcuts import render
from django.views.generic import CreateView, UpdateView
from .models import Produto
from .forms import ProdutoForm


def produto_list(request):
    template_name = 'produto_list.html'
    objects = Produto.objects.all()
    context = {'object_list': objects}
    return render(request, template_name, context)

def produto_detail(request, pk):
    template_name = 'produto_detail.html'
    obj = Produto.objects.get(pk=pk)
    context = {'object': obj}
    return render(request, template_name, context)

def produto_add(request):
    template_name = 'produto_form.html'
    return render(request, template_name)


class ProdutoCreate(CreateView):
    model = Produto
    template_name = 'produto_form.html'
    form_class = ProdutoForm

class ProdutoUpdate(UpdateView):
    model = Produto
    template_name = 'produto_form.html'
    form_class = ProdutoForm


def produto_json(request, pk):
    ''' Retorna o produto, id e estoque '''
    produto = Produto.objects.filter(pk=pk)
    data = [item.to_dict_json() for item in produto]
    return JsonResponse({'data': data})

core/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shotcut icon" href="http://www.djangoproject.com/favicon.ico">
    <title>Estoque</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <style>
      body {
        margin-top: 60px; 
      }
      .ok {
          color: green;
      }
      .no {
          color: red
      }
    </style>

    {% block css %}{% endblock css %}

  </head>
  <body>

    {% include "includes/nav.html" %}
    
    <div class="container">
      {% block content %}{% endblock content%}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    {% block js %}{% endblock js %}
  </body>
</html>

core/templates/includes/nav.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href="#">Estoque</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'core:index' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'produto:produto_list' %}">Produtos</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Estoque</a>
                <div class="dropdown-menu" aria-labelledby="dropdown01">
                    <a class="dropdown-item" href="{% url 'estoque:estoque_entrada_list' %}">Entrada</a>
                    <a class="dropdown-item" href="{% url 'estoque:estoque_saida_list' %}">Saída</a>
                </div>
            </li>
        </ul>
    </div>
</nav>

core/templates/index.html
{% extends 'base.html' %}

{% block content %}

<div class="jumbotron">
  <div class="container">
    <h1>Bem-vindo!</h1>
    <p>Este é um sistema para controle de estoque.</p>
    <p>
      <a href="https://github.com/jonathan-mothe/estoque">Veja no GitHub</a>
    </p>
  </div>
</div>

{% endblock content %}

estoque/templates/estoque_entrada_detail.html
{% extends 'base.html' %}

{% block content %}

<a href="{% url 'estoque:estoque_entrada_list' %}">Voltar</a>

<h1>{{ object }}</h1>

<div class="col-sm-6">
    <table class="table table-user-information">
        <tbody>
            <tr>
                <th class="text-right">NF</th>
                <td>{{ object.nf_formated }}</td>
            </tr>
            <tr>
                <th class="text-right">Data</th>
                <td>{{ object.created }}</td>
            </tr>
            <tr>
                <th class="text-right">Funcionário</th>
                <td>{{ object.funcionario.first_name }}</td>
            </tr>
        </tbody>
    </table>
</div>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Produto</th>
            <th>Quantidade</th>
            <th>Saldo</th>
        </tr>
    </thead>
    <tbody>
        {% for obj in object.estoques.all %}
            <tr>
                <td>{{ obj.produto }}</td>
                <td>{{ obj.quantidade }}</td>
                <td>{{ obj.saldo }}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock content %}

estoque/templates/estoque_entrada_form.html
{% extends 'base.html' %}

{% load widget_tweaks %}
{% load bootstrap %}

{% block css %}

    <style>
        span.required:after {
            content: '*';
            color: red
        }
        .form-control {
            margin: 10px;
        }
    </style>

{% endblock css %}

{% block content %}

<a href="{% url 'estoque:estoque_entrada_list' %}">Voltar</a>

<div class="row">
    <div class="cols">
        <form method="POST" novalidate>
            {% csrf_token %}
            <legend style="border-bottom: 1px solid #e5e5e5;">Estoque Entrada</legend>

            <div class="row">
                <div class="col-sm-6">
                    {% for field in form.visible_fields %}
                        <div class="form-group{% if field.errors %} has-error {% endif %}">
                            <label for="{{ field.id_for_label }}">
                                {% if field.field.required %}
                                    <span class="required">{{ field.label }} </span>
                                {% else %}
                                    {{ field.label }}
                                {% endif %}
                            </label>
                            {% render_field field class="form-control" %}
                            {% for error in field.errors %}
                                <span class="text-muted">{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% endfor %}
                    {{ formset.management_form }}
                </div>
            </div>
            
            <div class="row">
                <div class="col-sm-12">
                    <legend style="border-bottom: 1px solid #e5e5e5;">Produtos</legend>
                    <div id="estoque" class="form-inline">
                        {% for item_estoque_form in formset %}
                            <div id="item-{{ forloop.counter0 }}" class="form-group">
                                {{ item_estoque_form|bootstrap }}
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>

            <span id="add-item" class="btn btn-info" style="margin-top: 10px;">
                <i class="fa fa-plus"></i> Adicionar
            </span>

            <div class="row float-right">
                <div class="col sm-12" style="margin-top: 10px;">
                    <div class="form-inline buttons">
                        <button class="btn btn-primary" value="Save">
                            <i class="fa fa-floppy-o"></i>
                            Salvar
                        </button>
                        <a href="{% url 'estoque:estoque_entrada_list' %}" class="btn btn-danger">
                            <i class="fa fa-times"></i>
                            Cancelar
                        </a>
                    </div>
                </div>
            </div>

        </form>
    </div>
</div>

{% endblock content %}

{% block js %}

<script>
    $(document).ready(function() {
        // Insere classe no primeiro item do produto
        $('#id_estoque-0-produto').addClass('clProduto');
        $('#id_estoque-0-quantidade').addClass('clQuantidade');

        $('#add-item').click(function(ev) {
            ev.preventDefault();
            var count = $('#estoque').children().length;
            var tmplMarkup = $('#item-estoque').html();
            var compiledTmpl = tmplMarkup.replace(/__prefix__/g, count);
            $('div#estoque').append(compiledTmpl);

            // Update form count
            $('#id_estoque-TOTAL_FORMS').attr('value', count + 1);

            // some animate to scroll to view our new form
            $('html', 'body').animate({
                scrollTop: $('#add-item').position().top - 200 
            }, 800);

            $('#id_estoque-' + (count) + '-produto').addClass('clProduto');
            $('#id_estoque-' + (count) + '-quantidade').addClass('clQuantidade');
        });
    });
    
    let estoque
    let saldo
    let campo
    let quantidade

    $(document).on('change', '.clProduto', function() {
        let self = $(this)
        let pk = $(this).val()
        let url = '/produto/' + pk + '/json'

        $.ajax({
            url: url,
            type: 'GET',
            success: function(response) {
                estoque = response.data[0].estoque
                campo = self.attr('id').replace('produto', 'quantidade')
                // Remover o valor do campo 'quantidade'
                $('#'+campo).val('')
            },
            error: function(xhr) {

            }
        })
    });

    $(document).on('change', '.clQuantidade', function() {
        quantidade = $(this).val();
        saldo = Number(quantidade) + Number(estoque);
        campo = $(this).attr('id').replace('quantidade', 'saldo')
        // Atribui o saldo ao campo 'saldo'
        $('#'+campo).val(saldo)
    });

</script>

<script type="text/html" id="item-estoque">
    <div id="item-__prefix__" class="form-group">
        {{ formset.empty_form|bootstrap }}
    </div>
</script>

{% endblock js %}

estoque/templates/estoque_entrada_list.html
{% extends 'base.html' %}

{% block content %}

<h2>Estoque Entrada
    <span class="pull-right">
        <a href="{% url 'estoque:estoque_entrada_add' %}">
            <button type="button" class="btn btn-primary">
                <span class="fa fa-plus"></span> Adicionar
            </button>
        </a>
    </span>
</h2>

{% if object_list %}
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Item</th>
                <th>NF</th>
                <th>Data</th>
                <th>Funcionário</th>
            </tr>
        </thead>
        <tbody>
            {% for object in object_list %}
                <tr>
                    <td>
                        <a href="{{ object.get_absolute_url }}">{{ object }}</a>
                    </td>
                    <td>{{ object.nf_formated }}</td>
                    <td>{{ object.created }}</td>
                    <td>{{ object.funcionario.first_name }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% else %}
    <p class="alert alert-warning">Sem itens na lista</p>
{% endif %}

{% endblock content %}

estoque/templates/estoque_saida_detail.html
{% extends 'base.html' %}

{% block content %}

<a href="{% url 'estoque:estoque_saida_list' %}">Voltar</a>

<h1>{{ object }}</h1>

<div class="col-sm-6">
    <table class="table table-user-information">
        <tbody>
            <tr>
                <th class="text-right">NF</th>
                <td>{{ object.nf_formated }}</td>
            </tr>
            <tr>
                <th class="text-right">Data</th>
                <td>{{ object.created }}</td>
            </tr>
            <tr>
                <th class="text-right">Funcionário</th>
                <td>{{ object.funcionario.first_name }}</td>
            </tr>
        </tbody>
    </table>
</div>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Produto</th>
            <th>Quantidade</th>
            <th>Saldo</th>
        </tr>
    </thead>
    <tbody>
        {% for obj in object.estoques.all %}
            <tr>
                <td>{{ obj.produto }}</td>
                <td>{{ obj.quantidade }}</td>
                <td>{{ obj.saldo }}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock content %}

estoque/templates/estoque_saida_list.html
{% extends 'base.html' %}

{% block content %}

<h2>Estoque Saída
    <span class="pull-right">
        <a href="{$ url 'estoque:estoque_saida_add' %}">
            <button type="button" class="btn btn-primary">
                <span class="fa fa-plus"></span> Adicionar
            </button>
        </a>
    </span>
</h2>

{% if object_list %}
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Item</th>
                <th>NF</th>
                <th>Data</th>
                <th>Funcionário</th>
            </tr>
        </thead>
        <tbody>
            {% for object in object_list %}
                <tr>
                    <td>
                        <a href="{{ object.get_absolute_url }}">{{ object }}</a>
                    </td>
                    <td>{{ object.nf_formated }}</td>
                    <td>{{ object.created }}</td>
                    <td>{{ object.funcionario.first_name }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% else %}
    <p class="alert alert-warning">Sem itens na lista</p>
{% endif %}

{% endblock content %}

produto/templates/produto_detail.html
{% extends "base.html" %}

{% block content %}

    <a href="{% url 'produto:produto_list' %}">Voltar</a>

    <h1>{{ object }}
        <span class="pull-right">
            <a href="{% url 'produto:produto_edit' object.pk %}">
                <button type="button" class="btn btn-success">
                    <span class="fa fa-pencil"></span> Editar
                </button>
            </a>
        </span>
    </h1>

<div class="col-sm-6">
    <table class="table table-user-information">
    <tbody>
        <tr>
            <th class="text-right">Importado</th>
            <td>
                {% if object.importado %}
                    <i class="fa fa-check-circle ok"></i>
                {% else %}
                    <i class="fa fa-minus-circle no"></i>
                {% endif %}
            </td>
        </tr>
        <tr>
            <th class="text-right">NCM</th>
            <td>{{ object.ncm }}</td>
        </tr>
        <tr>
            <th class="text-right">Preço</th>
            <td>R$ {{ object.preco }}</td>
        </tr>
        <tr>
            <th class="text-right">Estoque</th>
            <td>{{ object.estoque }}</td>
        </tr>
        <tr>
            <th class="text-right">Estoque mínimo</th>
            <td>{{ object.estoque_minimo }}</td>
        </tr>
    </tbody>
    </table>
</div>

{% endblock content %}

produto/templates/produto_form.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block css %}
    <style>
        span.required:after {
            content: "*";
            color: red;
        }
    </style>
{% endblock css %}

{% block content %}

<form method="POST" novalidate>
    {% csrf_token %}
    {% for field in form.visible_fields %}
        <div class="form-group{% if field.errors %} has-error {% endif %}">
            <label for="{{ field.id_for_label }}">
                {% if field.field.required %}
                    <span class="required">{{ field.label }} </span>
                {% else %}
                    {{ field.label }}
                {% endif %}
            </label>
            {% render_field field class="form-control" %}
            {% for error in field.errors %}
                <span class="text-muted">{{ error }}</span>
            {% endfor %}
        </div>
    {% endfor %}
    <button type="submit" class="btn btn-success">Cadastrar</button>
</form>

{% endblock content %}

{% block js %}
<script>
    $('#id_importado').removeClass('form-control');
</script>
{% endblock js %}

produto/templates/produto_list.html
{% extends "base.html" %}

{% block content %}

<div class="page-header">
    <h2>Lista de Produtos
        <span class="pull-right">
            <a href="{% url 'produto:produto_add' %}">
                <button type="button" class="btn btn-primary">
                    <span class="fa fa-plus"></span> Adicionar
                </button>
            </a>
        </span>
    </h2>

    {% if object_list %}
     
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Importado</th>
                    <th>NCM</th>
                    <th>Produto</th>
                    <th>Preço</th>
                    <th class="text-center">Estoque</th>
                    <th class="text-center">Estoque mínimo</th>
                </tr>
            </thead>
            <tbody>
                {% for object in object_list %}
                    <tr>
                        <td>
                            {% if object.importado%}
                                <i class="fa fa-check-circle ok"></i>
                            {% else %}
                                <i class="fa fa-minus-circle no"></i>
                            {% endif %}
                        </td>
                        <td>{{ object.ncm }}</td>
                        <td>
                            <a href="{{ object.get_absolute_url }}">{{object.produto}}</a>
                        </td>
                        <td>R$ <span class="pull-right">{{ object.preco }}</span></td>
                        <td class="text-center">{{ object.estoque }}</td>
                        <td class="text-center">{{ object.estoque_minimo }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p class="alert alert warning">Sem itens na lista</p>
    {% endif %}

</div>

{% endblock content %}